### ISSUE TITLE
Origin game install error

### ISSUE THREAD

**Issue by Sporif** [Tk-Glitch/PKGBUILDS#157]
I tracked down the cause of the error when installing a game in Origin. [e4ca5db](https://github.com/wine-mirror/wine/commit/e4ca5dbec056c977bffce31bd7901aaec884f199) seems to be the culprit. I built wine-tkg-staging 4.5 with the parent commit of e4ca5db checked out for `dlls/kernel32/tests/pipe.c` and `server/named_pipe.c` and the error went away.  I've noticed no adverse affects to doing so but I've only tested for a few days. Of course this 'fix' means  the [bug](https://bugs.winehq.org/show_bug.cgi?id=41670) that e4ca5db fixes would still be present.

These are the commands I inserted into the PKGBUILD
```
git checkout 0a41f5b dlls/kernel32/tests/pipe.c
git checkout 6531f79 server/named_pipe.c
```

**Comment by Tk-Glitch** [comment]
Interestingly it's not the first time I ear about that commit..

**Comment by Tk-Glitch** [comment]
https://bugs.winehq.org/show_bug.cgi?id=46833

**Comment by Tk-Glitch** [comment]
Marking as invalid as while I can indeed include a workaround, it ultimately needs to be fixed upstream.

**Comment by Tk-Glitch** [comment]
As Origin is currently broken in 4.6, some might find the patch found [here](https://bugs.winehq.org/show_bug.cgi?id=45703#c27) to be useful.

**Comment by Sporif** [comment]
And [here's](https://bugs.winehq.org/show_bug.cgi?id=47027) the bug report for Origin crashing.

**Comment by Tk-Glitch** [comment]
I see Béla is there as well. Frogs everywhere :frog:

**Comment by Sporif** [comment]
This [patch](https://bugs.winehq.org/show_bug.cgi?id=47027#c8) also fixes the Origin crash.

**Comment by Tk-Glitch** [comment]
This issue can be considered resolved. The original install issue was fixed for a little while, and Origin was fixed in master yesterday. Closing !

**Comment by Sporif** [comment]
Uh I still get the install error on master, what commit was supposed to have fixed that?

**Comment by aufkrawall** [comment]
It works here, it also doesn't crash anymore with `STAGING_SHARED_MEMORY=1`. Perhaps re-enable it by default?

OT question probably not worth an extra ticket:
Is the child window patch included in staging by default? 3DCenter Filter Tester works without the patch provided by wine-tkg when wined3d10 is used.

**Comment by Sporif** [comment]
`STAGING_SHARED_MEMORY=1` doesn't crash Origin anymore, but I definitely still get the error... weird that no one else is experiencing it. What games did you try to install/update?

**Comment by aufkrawall** [comment]
I could install BF4, Garden Warfare and Mirror's Edge (this one doesn't run unfortunately) successfully. But there is that weird issue that the first install attempt after the download fails and you have to right-click the game and choose install again to make it work. Afaik this has always been the case however.

**Comment by Sporif** [comment]
Tried downloading Garden Warfare and `STAGING_SHARED_MEMORY=1` still seems to crash it so it doesn't actually look like that was fixed. But I see what you mean about bypassing the error, it's very glitchy but it's possible. Still, it was working without issues before wine 4.3.

**Comment by aufkrawall** [comment]
Tested again with clean wine prefixes and this time It also crashed for me with shared memory, while it didn't without.

**Comment by Sporif** [comment]
This is quite late but I found the cause of this issue, it was this wine commit: [e4ca5db](https://github.com/wine-mirror/wine/commit/e4ca5dbec056c977bffce31bd7901aaec884f199#diff-a4bad67e0197f35ab8330d5263b22154).
Reverting that is enough to fix the install error, though it presumably reintroduces the [BattlEye bug](https://bugs.winehq.org/show_bug.cgi?id=41670) that the commit fixed.

A simple revert works only with wine 4.3, this works for 4.4+:
```
diff --git a/server/named_pipe.c b/server/named_pipe.c
--- a/server/named_pipe.c
+++ b/server/named_pipe.c
@@ -1170,7 +1170,7 @@ static struct pipe_server *create_pipe_server( struct named_pipe *pipe, unsigned
     server->pipe_end.server_pid = get_process_id( current->process );
     init_async_queue( &server->listen_q );
 
-    list_add_tail( &pipe->listeners, &server->entry );
+    list_add_head( &pipe->listeners, &server->entry );
     if (!(server->pipe_end.fd = alloc_pseudo_fd( &pipe_server_fd_ops, &server->pipe_end.obj, options )))
     {
         release_object( server );
```
