### ISSUE TITLE
nier: automata crashes on start with *** stack smashing detected ***: <unknown> terminated

### ISSUE THREAD

**Issue by soredake** [Tk-Glitch/PKGBUILDS#219]
<details><summary>full log</summary>
<p>

```
Running /usr/bin/wine /home/bausch/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe -no-cef-sandbox -console steam://rungameid/524220
gamemodeauto: 
gamemodeauto: 
0030:fixme:process:ProcessIdToSessionId Unsupported for other processes.
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
ILocalize::AddFile() failed to load file "public/steambootstrapper_russian.txt".
0030:fixme:ver:GetCurrentPackageId (0x34fe24 (nil)): stub
Waiting on children
Exit with returncode 0
Running /usr/bin/wine /home/bausch/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe -no-cef-sandbox -console steam://rungameid/524220
gamemodeauto: 
gamemodeauto: 
user.reg:958: Malformed value '"HDA ATI HDMI HDMI/DP,pc"=3 (js)"="disabled"'
000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000b:fixme:winediag:start_process Wine TkG 4.9 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
000f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0012:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0014:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0025:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:shcore:SetCurrentProcessExplicitAppUserModelID L"Valve.Steam.Client": stub
0009:fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f007050, 0x3f04a1d8, 0x3f04a1d0) stub.
0009:fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f007050, 0x3f04a210, 0x3f04a208) stub.
0009:fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f007050, 0x3f04a1a0, 0x3f04a198) stub.
0009:fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 0x3f007050, 0x3f04a248, 0x3f04a240) stub.
0009:fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 0x3f007050, 0x3f04a280, 0x3f04a278) stub.
0009:fixme:process:SetProcessShutdownParameters (00000100, 00000000): partial stub.
0009:fixme:shcore:SetCurrentProcessExplicitAppUserModelID L"Valve.Steam.Client": stub
0009:err:rawinput:find_hid_devices Failed to open device file L"\\\\?\\HID#VID_054C&PID_09CC&IG_0#33041&030000004C050000CC09000011810000&1&2#{4D1E55B2-F16F-11CF-88CB-001111000030}", error 2.
0009:fixme:win:RegisterDeviceNotificationW (hwnd=0x20066, filter=0x34e600,flags=0x00000004) returns a fake device notification handle!
002f:fixme:win:RegisterDeviceNotificationW (hwnd=0x20072, filter=0x2cafdec,flags=0x00000000) returns a fake device notification handle!
0009:fixme:imm:ImmGetOpenStatus (009AC270): semi-stub
0009:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7x64\\steamwebhelper.exe"
0009:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7x64\\steamwebhelper.exe"
0009:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\logs\\cef_log.txt"
0009:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\logs\\cef_log.txt"
0009:fixme:dwmapi:DwmSetWindowAttribute (000100AA, 2, 0034DEAC, 4) stub
0009:fixme:dwmapi:DwmExtendFrameIntoClientArea (000100AA, 0034DE9C) stub
0031:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:advapi:StopTraceA (0, "Steam Event Tracing", 0x34de34) stub
0009:fixme:advapi:StartTraceA (0x34dec0, "Steam Event Tracing", 0x34de34) stub
0009:fixme:advapi:OpenTraceA 0x34dc00: stub
0009:fixme:advapi:EnableTrace (1, 0x10, 4, {22fb2cd6-0e7b-422b-a0c7-2fad1fd0e716}, cafe4242): stub
0009:fixme:advapi:CloseTrace cafe4242: stub
0034:fixme:advapi:ProcessTrace 0x80972058 1 (nil) (nil): stub
0031:fixme:nvapi:unimplemented_stub function 0x694d52e is unimplemented!
0031:fixme:nvapi:unimplemented_stub function 0x375dbd6b is unimplemented!
0031:fixme:shcore:SetCurrentProcessExplicitAppUserModelID L"Valve.Steam.Client": stub
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
003f:fixme:win:RegisterDeviceNotificationA (hwnd=0x100c4, filter=0x4eaf8cc,flags=0x00000004) returns a fake device notification handle!
0040:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
0040:fixme:wbemprox:client_security_SetBlanket 0xf6c759ec, 0x314afc0, 10, 0, (null), 3, 3, (nil), 0x00000000
0040:fixme:wbemprox:client_security_Release 0xf6c759ec
0028:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0040:fixme:ntdll:server_ioctl_file Unsupported ioctl 700a0 (device=7 access=0 func=28 method=0)
0040:fixme:ntdll:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
0040:fixme:wbemprox:enum_class_object_Next timeout not supported
0028:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0040:fixme:ntdll:server_ioctl_file Unsupported ioctl 700a0 (device=7 access=0 func=28 method=0)
0037:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0039:fixme:iphlpapi:NotifyAddrChange (Handle 0xb3046c, overlapped 0xb30470): stub
gamemodeauto: 
004a:fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
004a:fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0049:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:dwmapi:DwmExtendFrameIntoClientArea (000100C6, 0034E2F4) stub
0049:fixme:win:RegisterTouchWindow (0x20050 00000003): stub
Z:\home\bausch\.local\share\lutris\runners\winesteam\prefix64\drive_c\Program Files (x86)\Steam\bin\cef\cef.win7x64\steamwebhelper.exe: invalid option -- `-n'
Try 'steamwebhelper.exe --help' for more information.
System page size: 4096
Could not find page for trampoline in +/- 2GB range of function to hook
Error allocating trampoline memory (no memory within +/-2gb? prior failures?)
0037:fixme:ver:GetCurrentPackageId (0x24fd10 (nil)): stub
[0608/143042.724:ERROR:registration_protocol_win.cc(84)] TransactNamedPipe:  . (0x6D)
0031:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0049:fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
0009:fixme:dwrite:dwritefactory_CreateMonitorRenderingParams (0x1): monitor setting ignored
0031:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
[0608/143042.868:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: browser
0031:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x24ef90, (nil) 0x24ef8c
0031:fixme:nls:get_dummy_preferred_ui_language (0x38 0x24ef90 (nil) 0x24ef8c) returning a dummy value (current locale)
0031:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x24ef90, 0x4eebe0 0x24ef8c
0031:fixme:nls:get_dummy_preferred_ui_language (0x38 0x24ef90 0x4eebe0 0x24ef8c) returning a dummy value (current locale)
0057:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
0057:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
0057:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
0057:fixme:shell:CustomDestinationList_BeginList 0x5d3e3d0 (0x4fcfa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x4fcfa54): stub
0031:fixme:winsock:WSALookupServiceBeginW (0x24eac0 0x00000ff0 0x24eb38) Stub!
[0608/143043.272:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
0031:fixme:iphlpapi:NotifyAddrChange (Handle 0x24ed48, overlapped 0x5583d0): stub
005c:fixme:wtsapi:WTSRegisterSessionNotification Stub 0x30046 0x00000001
gamemodeauto: 
0031:fixme:win:RegisterDeviceNotificationW (hwnd=0x200d2, filter=0x24eb08,flags=0x00000000) returns a fake device notification handle!
0031:fixme:win:GetDisplayConfigBufferSizes (0x2 0x24e7b4 0x24e7b0): stub
0052:fixme:file:FindFirstFileExW flags not implemented 0x00000002
0052:fixme:file:FindFirstFileExW flags not implemented 0x00000002
0053:fixme:wlanapi:WlanEnumInterfaces (0x1, (nil), 0x266edb0) semi-stub
0031:fixme:win:GetDisplayConfigBufferSizes (0x2 0x24edd4 0x24edd0): stub
0066:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0069:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0xffdd27f0, 0xffde0030, 0xffde0048) stub.
0069:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0xffdd2560, 43) stub
0069:fixme:win:RegisterTouchWindow (0x300d8 00000003): stub
0069:fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
0069:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
[0608/143044.203:ERROR:registration_protocol_win.cc(56)] CreateFile:   . (0x2)
0066:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
[0608/143044.204:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: gpu-process
0077:fixme:time:QueryThreadCycleTime (0x11c,0x1fafb60): stub!
info:  Game: steamwebhelper.exe
info:  DXVK: v1.2.1
info:  Found config file: /home/bausch/.config/dxvk.conf
info:  Effective configuration:
info:    d3d11.relaxedBarriers = True
info:    d3d11.allowMapFlagNoWait = True
info:    d3d11.samplerAnisotropy = 16
info:    d3d11.maxTessFactor = 8
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX 560 Series:
info:    Driver: 2.0.91
info:    Vulkan: 1.1.108
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
0079:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
0079:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
0079:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
0079:fixme:shell:CustomDestinationList_BeginList 0x5d8dc98 (0x689fa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x689fa54): stub
info:  DXVK: Read 0 valid state cache entries
info:  DXVK: Using 12 compiler threads
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  D3D11DeviceContext::QueryInterface: Unknown interface query
warn:  b4e3c01d-e79e-4637-91b2-510e9f4c9b8f
err:   DXGI: CheckInterfaceSupport: Unsupported interface
err:   54ec77fa-1377-44e6-8c32-88fd5f44c84c
[0608/143046.788:ERROR:angle_platform_impl.cc(47)] populateRenderer11DeviceCaps(900): Error querying driver version from DXGI Adapter.
warn:  D3D11Device::GetDeviceRemovedReason: Stub
0039:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0009:fixme:imm:ImmReleaseContext (000100C6, 05D61CF8): stub
0009:fixme:dwmapi:DwmExtendFrameIntoClientArea (000400DE, 0034DF40) stub
009b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:dwmapi:DwmExtendFrameIntoClientArea (000100F6, 0034DA98) stub
0009:fixme:win:RegisterDeviceNotificationA (hwnd=0x100f6, filter=0x34dc94,flags=0x00000004) returns a fake device notification handle!
[0608/143048.926:ERROR:registration_protocol_win.cc(56)] CreateFile:   . (0x2)
009b:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
[0608/143048.928:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: renderer
0009:err:ole:CoGetClassObject class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
0009:err:ole:CoGetClassObject class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
0009:err:ole:create_server class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
0009:fixme:ole:CoGetClassObject CLSCTX_REMOTE_SERVER not supported
0009:err:ole:CoGetClassObject no class object {294935ce-f637-4e7c-a41b-ab255460b862} could be created for context 0x17
0009:fixme:dwmapi:DwmExtendFrameIntoClientArea (00030130, 0034E154) stub
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
00a8:fixme:hnetcfg:fw_apps_get__NewEnum 0615FAA0, 0734F980
00a8:fixme:hnetcfg:fw_app_put_ProcessImageFileName 0615F8E8, L"Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\Steam.exe"
00a8:fixme:mpr:WNetGetUniversalNameW (L"Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\Steam.exe", 0x00000001, (nil), 0x734f954): stub
00a8:fixme:hnetcfg:fw_app_put_Name 0615F8E8, L"Steam"
00a8:fixme:hnetcfg:fw_app_put_Enabled 0615F8E8, -1
00a8:fixme:hnetcfg:fw_apps_Add 0615F948, 0615F8E8
00a8:fixme:hnetcfg:netfw_rules_get__NewEnum 06187948, 0734F97C
00a8:fixme:hnetcfg:fw_apps_get__NewEnum 06184180, 0734F980
00a8:fixme:hnetcfg:fw_app_put_ProcessImageFileName 06187948, L"Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7x64\\steamwebhelper.exe"
00a8:fixme:mpr:WNetGetUniversalNameW (L"Z:\\home\\bausch\\.local\\share\\lutris\\runners\\winesteam\\prefix64\\drive_c\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7x64\\steamwebhelper.exe", 0x00000001, (nil), 0x734f954): stub
00a8:fixme:hnetcfg:fw_app_put_Name 06187948, L"Steam Web Helper"
00a8:fixme:hnetcfg:fw_app_put_Enabled 06187948, -1
00a8:fixme:hnetcfg:fw_apps_Add 06184180, 06187948
00a8:fixme:hnetcfg:netfw_rules_get__NewEnum 031D5CD8, 0734F97C
009b:fixme:time:QueryThreadCycleTime (0xfffffffffffffffe,0x24e820): stub!
00af:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00af:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00af:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00af:fixme:shell:CustomDestinationList_BeginList 0x5d32880 (0x758fa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x758fa54): stub
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0031:fixme:dwmapi:DwmIsCompositionEnabled 000000000024E884
0031:fixme:win:RegisterTouchWindow (0x200ca 00000002): stub
005c:fixme:wtsapi:WTSRegisterSessionNotification Stub 0x30050 0x00000000
0009:fixme:dwmapi:DwmExtendFrameIntoClientArea (000300C8, 0034DEC4) stub
0009:fixme:dwmapi:DwmExtendFrameIntoClientArea (00010168, 0034DD84) stub
0031:fixme:win:RegisterTouchWindow (0x10172 00000002): stub
00b8:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00b8:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00b8:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00b8:fixme:shell:CustomDestinationList_BeginList 0x61b2618 (0x76afa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x76afa54): stub
00ba:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00ba:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00ba:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00ba:fixme:shell:CustomDestinationList_BeginList 0x6066a40 (0x758fa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x758fa54): stub
0031:fixme:dwmapi:DwmGetCompositionTimingInfo (0000000000000000 000000000024ECD8)
0039:fixme:volume:GetVolumeNameForVolumeMountPointW Mounted Folders are not yet supported
00b6:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
005d:fixme:file:ReplaceFileW Ignoring flags 2
005d:fixme:file:FindFirstFileExW flags not implemented 0x00000002
005e:fixme:file:ReplaceFileW Ignoring flags 2
005d:fixme:file:FindFirstFileExW flags not implemented 0x00000002
005e:fixme:file:FindFirstFileExW flags not implemented 0x00000002
005e:fixme:file:FindFirstFileExW flags not implemented 0x00000002
0073:fixme:file:ReplaceFileW Ignoring flags 2
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
[0608/143056.090:ERROR:registration_protocol_win.cc(56)] CreateFile:   . (0x2)
00b6:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
[0608/143056.092:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: renderer
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
00b6:fixme:time:QueryThreadCycleTime (0xfffffffffffffffe,0x24e820): stub!
00d5:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
00d5:fixme:ver:GetCurrentPackageId (0x24fd10 (nil)): stub
*** stack smashing detected ***: <unknown> terminated
00d2:err:seh:NtRaiseException Unhandled exception code 80000101 flags 1 addr 0x7f1f08f3582f
00d8:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00d8:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00d8:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00d8:fixme:shell:CustomDestinationList_BeginList 0x6068af0 (0x76afa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x76afa54): stub
00da:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00da:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00da:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00da:fixme:shell:CustomDestinationList_BeginList 0x5d927c8 (0x758fa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x758fa54): stub
0073:fixme:cryptnet:verify_cert_revocation_from_aia_ext OCSP URL = L"http://ocsp.int-x3.letsencrypt.org"
[0608/143058.195:WARNING:cert_verify_proc_win.cc(104)] Unknown error -2146762482 mapped to net::ERR_FAILED
00dc:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
[0608/143058.916:ERROR:registration_protocol_win.cc(56)] CreateFile:   . (0x2)
00dc:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
[0608/143058.917:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: gpu-process
00df:fixme:time:QueryThreadCycleTime (0x11c,0x1fafb60): stub!
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: steamwebhelper.exe
info:  DXVK: v1.2.1
info:  Found config file: /home/bausch/.config/dxvk.conf
info:  Effective configuration:
info:    d3d11.relaxedBarriers = True
info:    d3d11.allowMapFlagNoWait = True
info:    d3d11.samplerAnisotropy = 16
info:    d3d11.maxTessFactor = 8
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX 560 Series:
info:    Driver: 2.0.91
info:    Vulkan: 1.1.108
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  17399d75-964e-4c03-99f8-9d4fd196dd62
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: steamwebhelper.exe
info:  DXVK: v1.2.1
info:  Found config file: /home/bausch/.config/dxvk.conf
info:  Effective configuration:
info:    d3d11.relaxedBarriers = True
info:    d3d11.allowMapFlagNoWait = True
info:    d3d11.samplerAnisotropy = 16
info:    d3d11.maxTessFactor = 8
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX 560 Series:
info:    Driver: 2.0.91
info:    Vulkan: 1.1.108
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  17399d75-964e-4c03-99f8-9d4fd196dd62
System page size: 4096
Could not find page for trampoline in +/- 2GB range of function to hook
Error allocating trampoline memory (no memory within +/-2gb? prior failures?)
00dc:fixme:ver:GetCurrentPackageId (0x24fd10 (nil)): stub
00ea:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00ea:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00ea:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00ea:fixme:shell:CustomDestinationList_BeginList 0x3472d20 (0x76afa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x76afa54): stub
0031:fixme:win:RegisterTouchWindow (0x30188 00000003): stub
0031:fixme:dwmapi:DwmSetWindowAttribute (0000000000030188, 2, 000000000024DDE8, 4) stub
0031:fixme:dwmapi:DwmExtendFrameIntoClientArea (0000000000030188, 000000000024DDA0) stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETTASKBARPOS, hwnd=0000000000000000): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=3): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=1): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=0): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=2): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETTASKBARPOS, hwnd=0000000000000000): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=3): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=1): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=0): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=2): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETTASKBARPOS, hwnd=0000000000000000): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=3): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=1): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=0): stub
0014:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETAUTOHIDEBAR, hwnd=0000000000000000, edge=2): stub
0031:fixme:win:RegisterTouchWindow (0x30164 00000002): stub
0031:fixme:win:RegisterTouchWindow (0x30162 00000002): stub
00ed:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00ed:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00ed:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00ed:fixme:shell:CustomDestinationList_BeginList 0x6212250 (0x758fa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x758fa54): stub
00fc:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00fc:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00fc:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00fc:fixme:shell:CustomDestinationList_BeginList 0x6198158 (0x76afa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x76afa54): stub
00fe:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00fe:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
00fe:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
00fe:fixme:shell:CustomDestinationList_BeginList 0x61b2130 (0x758fa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x758fa54): stub
0100:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
0100:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
0100:fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
0100:fixme:shell:CustomDestinationList_BeginList 0x5de6658 (0x76afa48 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x76afa54): stub
0039:fixme:volume:GetVolumeNameForVolumeMountPointW Mounted Folders are not yet supported
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0039:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
```

</p>
</details>

`wine-tkg` build an hour ago on `archlinux`

Game works with `ge-protonified-4.9-x86_64` from lutris.

**Comment by soredake** [comment]
Borderlands GOTY Enhanced crashes too.

**Comment by gulafaran** [comment]
winecfg and just opening the "Drives" tab does the same

**Comment by Tk-Glitch** [comment]
Sounds like an upstream regression. The content of your `last_build_config.log` or a commit number at the very least would help. I wasn't able to reproduce the issue on staging 4.9.r15.g5681cd54.

**Comment by soredake** [comment]
[last_build_config.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/3269422/last_build_config.zip)

**Comment by Tk-Glitch** [comment]
Thanks. I've had more feedback from other users since, and so far it might be related to nvidia. Are you using nvidia GPUs, and if you do, what driver are you using?

**Comment by soredake** [comment]
I am using rx 560.

**Comment by gulafaran** [comment]
im using a vega56 on amdgpu so its not only nvidia

**Comment by Tk-Glitch** [comment]
That clears it up. Did you try with wined3d instead of DXVK? The GPU I have access to right now (not at home) isn't vulkan capable, and whatever I tried I'm unable to reproduce the issue.
The bug was reported on wine builds first so it's unlikely to be proton-related.

Can we all confirm that wine staging 1998c0570d22f804fe229e75e17b282619927071 is fine?
That's `_staging_version="1998c05"` in your .cfg

**Comment by idprophecy** [comment]
Radeon user here. The latest revision behaves exactly like above mentioned. 1998c0570d22f804fe229e75e17b282619927071 works just fine, can confirm on my machine.

**Comment by soredake** [comment]
Yes, with this commit my games work again.

**Comment by Tk-Glitch** [comment]
Did the issue get fixed by the last wave/4.10 release?

**Comment by idprophecy** [comment]
Yeah, seems it got fixed. No issues have occured to me since 4.10.

**Comment by Tk-Glitch** [comment]
I saw Zeb had pending stuff that got merged with the release. That's good news.

**Comment by idprophecy** [comment]
Or not, started to crash again. But here is what I found out. If I have my external HDD plugged in, it crashes. If not, everything works just fine.

**Comment by Tk-Glitch** [comment]
Interesting, that sounds exactly like an issue I reported months ago to... Zeb. And it got fixed at the time. I think it was somewhat well hidden. It makes sense regarding the recent PnP changes, and that also would explain why I can't reproduce it on my laptop.

**Comment by Tk-Glitch** [comment]
He has new patches pending.. Worth checking them out I guess :
https://www.winehq.org/pipermail/wine-devel/2019-June/147329.html
https://www.winehq.org/pipermail/wine-devel/2019-June/147331.html
https://www.winehq.org/pipermail/wine-devel/2019-June/147330.html

**Comment by idprophecy** [comment]
Will give them a shot when I'll get to my laptop.

**Comment by XeonDead** [comment]
I have a feeling https://www.winehq.org/pipermail/wine-devel/2019-June/147330.html was already applied - it does not apply cleanly to 4.10.r1.
Other two are applied and building.

**Comment by XeonDead** [comment]
The https://www.winehq.org/pipermail/wine-devel/2019-June/147330.html should be rebased and applied.
Other two patches didn't solve the issue.

**Comment by Tk-Glitch** [comment]
More patches are now pending, so it might yet again get fixed in the next wave or two :frog:
If it isn't, we'd need that someone who can reproduce it gets a log from either clean mainline or staging (you can build that with the `_LOCAL_PRESET` variable in cfg) and post that over winehq.

**Comment by XeonDead** [comment]
To clarify: 
_local_preset=staging still crashes.
_local_preset=mainline works.
This is something on staging Wine branch.

**Comment by benjamimgois** [comment]
i also got this error in killer instinct and a hat in time.

*** stack smashing detected ***

**Comment by Tk-Glitch** [comment]
I was able to reproduce the issue on my main machine with both Warframe, Nier : Automata and Borderlands GOTY enhanced.
Rebuilding mingw (using the automation script I'm providing in the repo) then wine against current staging master - b5055c0b - fixed it all (I also recompiled Faudio before wine for good measure as I was using an older build). The three games are working again here.

**Comment by XeonDead** [comment]
Confirming - rebuilding mingw, faudio and wine at latest GCC (9.1.0) fixed the issue for me, too.

**Comment by soredake** [comment]
Tested f4 and deus ex md, they are working, will test borderlands and nier later.

**Comment by idprophecy** [comment]
Can confirm it works again as of the latest revision.

**Comment by benjamimgois** [comment]
In the latest revision (wine 4.10-r7) Killer instinct is working again. A hat in time runs but i had some slowdowns ans system freezes that doesn't happen before.

**Comment by Tk-Glitch** [comment]
The issue has been confirmed as fixed by multiple sources in addition to here. I'll consider this fixed.
