### ISSUE TITLE
I can't to build it because patching errors

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#26]
Hi! Thank you for your work!
I use Arch Linux.
My [customization.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2476822/customization.zip) config file is here.
But, unfortunately, I can't to build your PKGBUILD because the patching errors:
-------------------------
Checking patch include/wine/server_protocol.h...
Hunk #1 succeeded at 5899 (offset 254 lines).
error: while searching for:
    REQ_set_job_limits,
    REQ_set_job_completion_port,
    REQ_terminate_job,
    REQ_NB_REQUESTS
};

error: patch failed: include/wine/server_protocol.h:5937
error: include/wine/server_protocol.h: patch does not apply
Checking patch server/Makefile.in...
Checking patch server/esync.c...
Checking patch server/protocol.def...
Hunk #1 succeeded at 3979 (offset 129 lines).
Checking patch server/request.h...
error: while searching for:
DECL_HANDLER(set_job_limits);
DECL_HANDLER(set_job_completion_port);
DECL_HANDLER(terminate_job);

#ifdef WANT_REQUEST_HANDLERS

error: patch failed: server/request.h:402
error: server/request.h: patch does not apply
Checking patch server/trace.c...
Hunk #1 succeeded at 4687 (offset 148 lines).
Context reduced to (2/2) to apply fragment at 4687
error: while searching for:
    (dump_func)dump_set_job_limits_request,
    (dump_func)dump_set_job_completion_port_request,
    (dump_func)dump_terminate_job_request,
};

static const dump_func reply_dumpers[REQ_NB_REQUESTS] = {

error: patch failed: server/trace.c:4831
error: server/trace.c: patch does not apply
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by Tk-Glitch** [comment]
Hi @Kerrung !
I've seen that before.. Please delete any `esync.tgz` archive in the PKGBUILD's folder as well as the `src` dir, then try running makepkg again.

**Comment by Tk-Glitch** [comment]
I just pushed https://github.com/Tk-Glitch/PKGBUILDS/commit/a076032497e4c33e106b84283e0631170e373cc5 that should finally get rid of the issue for good.

**Comment by Kerrung** [comment]
![screenshot from 2018-10-15 12-17-02](https://user-images.githubusercontent.com/36989404/46935942-2af1ad00-d076-11e8-9d60-747679e75823.png)

**Comment by Tk-Glitch** [comment]
You don't seem to have deleted the src dir.

**Comment by Tk-Glitch** [comment]
I have just pushed https://github.com/Tk-Glitch/PKGBUILDS/commit/92ae829bf48a5d5fd7ee408c33d71af46c0b4677 that will clean your srcdir further than before to fix funky things when changing config. I can't reproduce the issue anymore (while no deleting src dir) with your config after that commit. I'll wait for your feedback.

**Comment by Kerrung** [comment]
No, I deleted the src dir, but this did not solve the issue.
I tried 92ae829 but again it did not help me and did not change anything.
I changed the source section because otherwise makepkg could not find the patches listed in it, even though I disabled them in the configuration file. I have attached my version of PKGBUILD here with my editing. Please look at it and say, can this be the cause of this issue? Thank you.
[PKGBUILD](https://github.com/Tk-Glitch/PKGBUILDS/files/2478228/PKGBUILD.zip)

**Comment by Kerrung** [comment]
The package compiled successfully when I did what you told me to do. Thank you.
