### ISSUE TITLE
Nostale Gameshop doesn't work with d9vk (child window d3d9 -> d3d11)

### ISSUE THREAD

**Issue by jona-1993** [Tk-Glitch/PKGBUILDS#341]
I don't know if it's your bug or winehq. I sended also that to winehq.

The issue is here:

https://github.com/Joshua-Ashton/d9vk/issues/186

**Comment by fluffykittyrevenge** [comment]
While I empathize with you wanting to get your game to work and trying every avenue available, using both Wine-TKG and D9VK won't get you any help at WineHQ where they really only support Wine, Wine Staging, and their DX methods. 

First line in the README here is, paraphrased, do not post bugs from here at WineHQ.  It's also repeated during the compilation for extra emphasis. :bear: :bear: :bear: :bear:

Could post your terminal output in an attached text file?  There might be something in it that helps narrow down the cause of your issue.

It would also help if you posted your last build config so we can build the same build you're using as well as see what patches you're using to see if one of them is the cause since you haven't said if you've tested with vanilla Wine or only TKG builds.

**Comment by jona-1993** [comment]
Yes, sorry ;)

I used lutris-4.16-x86_64.

Logs: https://pastebin.com/Gc5qt7nS

I displayed the workshop 2x.

With wined3d, it works.

**Comment by fluffykittyrevenge** [comment]
No problems.  

This is a shot in the dark, but have you tried launching the game with "LC_ALL=C".  There are quite a few locale errors in there and launching stuff with that environment variable has helped with those in the past.

Are you using the Steam or Website version of this game?  And are you using D9VK from dxvk-tools or from winetricks or just with whatever Lutris is providing with that runtime (seeing the version doesn't tell me where it came from)? 

I have to go to work now, but I don't have anything going on tonight and I can see if I can reproduce these errors on an RX 580.

**Comment by jona-1993** [comment]
I use the website version (but the new launcher has an issue, I update the game with Windows currently. The bug is reported.).

With Steam, the workshop is opened with the Steam overlay, but you have the same issue with the help window (press F11). 

You can also launch the game with wine:
wine ".../Steam/steamapps/common/NosTale/NostaleClientX.exe EntwellNostaleClient"

I use the last build of D9VK: https://git.froggi.es/joshua/d9vk/-/jobs/

I do not have any changes with LC_ALL=C. Same logs..

**Comment by fluffykittyrevenge** [comment]
Sorry about the delay.  What should have been a four hour day turned into a 10 hour day and crappy weather this weekend had me occupied with stuff around the house.

So far I've had no issues with the first launcher installed under GameforgeLive.  Downloading and installing Nostale with it worked as expected as well as clicking on Play started its launcher and update process which eventually downloaded and wanted to use thse GameforgeLoginMS2 launcher that had issues and I haven't been able to get that running.

Just trying things out,  `wine "~/.wine/drive_c/Program Files (x86)/GameforgeLive/Games/USA_eng/NosTale/Nostale.exe"` prompted the game to download yet another client under GameforgeClient, ran with `wine "~/.wine/drive_c/Program Files (x86)/GameforgeClient/gfclient.exe"`, which does work and that wanted to download the game a 2nd time so that's where I'm at now with a download fluctuating with between 30-60 minutes left...slow servers :turtle: 

Using wine-tkg with this config:
[customization.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3722076/customization.cfg.txt)

And d9vk and a few other things via winetricks:
```
winetricks corefonts
winetricks d9vk
winetricks dxvk
```

**Comment by jona-1993** [comment]
I have an issue when I build wine with this "customization.cfg".
When I create a new wine prefix and execute something, I have this error:

wine: configuration in '/home/jona1993/Games/NostaleTest' has been updated.
wine client error:0: version mismatch 590/588.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?

I forgot something?
I created this prefix with "./wine". Why version mismatch?

**Comment by fluffykittyrevenge** [comment]
Do you happen to have a wine process running in the background?  That's usually the cause of that error.  I know that I've hand to manually kill various wine processes after trying the Nostale/Gameforge executables because they don't always exit cleanly.

Other than that, not sure.  It updated just fine with "winecfg" on my system.

**Comment by jona-1993** [comment]
No.. I don't have wine process. Verified with ps command. 

For build wine:
$ git clone https://github.com/Tk-Glitch/PKGBUILDS.git
$ cd PKGBUILDS/wine-tkg-git
(I replace the content of customization.cfg by your config)
$ ./non-makepkg-build.sh (I have Kubuntu 19.04)
$ cd src/wine-mirror-git/
$ ./configure --enable-win64
$ make -j4
-------
I delete ~/Games/NostaleTest if it exist.
$ WINEPREFIX=~/Games/NostaleTest ./wine winecfg

--> winetrick, launch, etc..

It's correct?

**Comment by Tk-Glitch** [comment]
Nope, not completely right.
You'll likely want to set your own installation path in customization.cfg (else it'll be installed in the `PKGBUILDS/wine-tkg-git/non-makepkg-builds` dir) :
```
#### NON-MAKEPKG OPTIONS (Won't affect makepkg builds) ####

# Set to the desired installation path for your build(s). A versioned dir containing your build will be created inside that target.
# Example: _nomakepkg_prefix_path="/home/frog" will install your build in /home/frog/wine-tkg-********
_nomakepkg_prefix_path=""
```
You don't have to do any extra step after running `non-makepkg-build.sh`. So that's basically:
```
$ git clone https://github.com/Tk-Glitch/PKGBUILDS.git
$ cd PKGBUILDS/wine-tkg-git (set customization.cfg options as desired)
$ ./non-makepkg-build.sh
```
Keep an eye out for compilation failure, especially on the 32-bit side. Ubuntu is terrible when it comes to 32-bit build dependencies for wine.

Then you need to run wine from its installed path, so for the default path and if PKGBUILDS was cloned in your home dir it would be :
`WINEPREFIX="/home/jona1993/Games/NostaleTest" "/home/jona1993/PKGBUILDS/wine-tkg-git/non-makepkg-builds/wine-tkg-***(version)/bin/wine" app.exe`

To run winecfg for that prefix:
`WINEPREFIX="/home/jona1993/Games/NostaleTest" "/home/jona1993/PKGBUILDS/wine-tkg-git/non-makepkg-builds/wine-tkg-***(version)/bin/winecfg"`

To run winetricks you might want to export the "WINE" var if you want to use your own build for it:
`WINEPREFIX="/home/jona1993/Games/NostaleTest" WINE="/home/jona1993/PKGBUILDS/wine-tkg-git/non-makepkg-builds/wine-tkg-***(version)/bin/wine" winetricks`

This is a necessary evil due to wine-tkg-git only packaging for pacman currently. So wine-tkg isn't installed system-wide.

**Comment by jona-1993** [comment]
Yes..

configure: error: gstreamer-1.0 base plugins 64-bit development files not found, GStreamer won't be supported.
This is an error since --with-gstreamer was requested.

It's strange, gstreamer1.0-plugins-base is installed (32 bit & 64 bit)
I used: sudo apt-get install --reinstall gstreamer1.0-plugins-base
But same issue..
Maybe because I have these directories ? Conflict?
-- 32 bit --
/usr/lib32
/usr/lib/i386-linux-gnu/
-- 64 bit --
/usr/lib64
/usr/lib/x86_64-linux-gnu/

**Comment by Tk-Glitch** [comment]
This is a very common issue. Could be 32-bit glib or multilib GCC and not directly 32-bit gstreamer package's fault.
If nothing seemingly fixes it, you can also disable gstreamer support for the 32-bit side by removing `--with-gstreamer` from `customization.cfg`'s `_configure_userargs32` option as a workaround:
```
# Sets custom configure-args for 32-bit, separated by a space (example: "--without-mingw --with-vkd3d")
_configure_userargs32="--with-x --with-gstreamer --with-xattr"
```

**Comment by jona-1993** [comment]
Or create a symbolic link? 
ln -s /usr/lib/x86_64-linux-gnu/gstreamer1.0 /usr/lib32/gstreamer1.0
...
...
...

It's not de best way, but it can works?

**Comment by fluffykittyrevenge** [comment]
Looking at Ubuntu's build script, the rules.txt below, for wine, they use custom set lib variables as well as had a patch for gstreamer in their patches.  The patch is for 4.2 but I updated it so it applies to master since the lines were just off.

```
description: avoid unneeded libgstbase dependency from winegstreamer.dll.so
author: Michael Gilbert <mgilbert@debian.org>

--- a/configure.ac
+++ b/configure.ac
@@ -1626,7 +1626,7 @@ WINE_NOTICE_WITH(pulse, [test -z "$PULSE
 dnl **** Check for gstreamer ****
 if test "x$with_gstreamer" != "xno"
 then
-    WINE_PACKAGE_FLAGS(GSTREAMER,[gstreamer-1.0 gstreamer-video-1.0 gstreamer-audio-1.0],,,,
+    WINE_PACKAGE_FLAGS(GSTREAMER,[gstreamer-1.0],,,,
         [ac_gst_incl=""
         for i in $GSTREAMER_CFLAGS
         do
@@ -1634,6 +1634,7 @@ then
                 -I*) ac_gst_incl="$ac_gst_incl $i";;
             esac
         done
+        GSTREAMER_LIBS="$GSTREAMER_LIBS -lgstvideo-1.0 -lgstaudio-1.0"
         GSTREAMER_CFLAGS=$ac_gst_incl
         CPPFLAGS="$ac_save_CPPFLAGS $GSTREAMER_CFLAGS"
         AC_CHECK_HEADER([gst/gst.h],

```
[rules.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3725791/rules.txt)

**Comment by fluffykittyrevenge** [comment]
> Or create a symbolic link?
> ln -s /usr/lib/x86_64-linux-gnu/gstreamer1.0 /usr/lib64/gstreamer1.0
> ...
> ...
> ...
> 
> It's not de best way, but it can works?

That way might, but it's dirty and I wouldn't recommend it as a long term solution.

**Comment by jona-1993** [comment]
wine build: Success

I disabled gstreamer, it doesn't work. I made a git pull before, but no..

Now, when I launch the game I have these errors:

0009:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
0009:err:module:LdrInitializeThunk "winevulkan.dll" failed to initialize, aborting
0009:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\media\\jona1993\\Data\\Program Shared\\Nostale_FR\\NostaleClientX.exe" failed, status c0000142
Waiting on children
All children gone
Exit with returncode 66


gstreamer isn't important?

**Comment by Tk-Glitch** [comment]
The error you get is unrelated to gstreamer. Do you have vulkan libs installed (32-bit ones as well)?

**Comment by jona-1993** [comment]
Yes, libvulkan1 and libvulkan1:i386 are installed.

With others TKG builds, d9vk works. It's strange..

**Comment by Tk-Glitch** [comment]
What about the build deps? What's the output of these, ran from `PKGBUILDS/wine-tkg-git` dir??
```
./non-makepkg-build.sh --deps64
./non-makepkg-build.sh --deps32
```

**Comment by jona-1993** [comment]
with --deps64:

creating Makefile rules... done
configure: creating ./config.status
config.status: creating Make.tmp
config.status: creating include/config.h
config.status: linking tools/winewrapper to wine
config.status: linking tools/winewrapper to wine64
config.status: executing include/stamp-h commands
config.status: executing tools/makedep commands
config.status: executing Makefile commands

configure: OpenCL 64-bit development files not found, OpenCL won't be supported.
configure: libhal 64-bit development files not found, no legacy dynamic device support.
configure: gstreamer-1.0 base plugins 64-bit development files not found, GStreamer won't be supported.

configure: Finished.  Do 'make' to compile Wine.

 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 
 
 with --deps32:
 
creating Makefile rules... done
configure: creating ./config.status
config.status: creating Make.tmp
config.status: creating include/config.h
config.status: linking tools/winewrapper to wine
config.status: executing include/stamp-h commands
config.status: executing tools/makedep commands
config.status: executing Makefile commands

configure: OpenCL 32-bit development files not found, OpenCL won't be supported.
configure: libhal 32-bit development files not found, no legacy dynamic device support.
configure: gstreamer-1.0 base plugins 32-bit development files not found, GStreamer won't be supported.
configure: libSDL2 32-bit development files not found, SDL2 won't be supported.
configure: libFAudio 32-bit development files not found, XAudio2 won't be supported.
configure: libvulkan and libMoltenVK 32-bit development files not found, Vulkan won't be supported.

configure: WARNING: libxslt 32-bit development files not found, xslt won't be supported.

configure: Finished.  Do 'make' to compile Wine.

 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 
 
 Interesting.. libvulkan 32 bit is installed. 
 with "sudo apt-get install libvulkan1:i386" , libvulkan is installed (version 1.1.121.0~rc2-1lunarg18.04.1.1)

**Comment by Tk-Glitch** [comment]
What about 32-bit libvulkan-devel?

**Comment by jona-1993** [comment]
after sudo apt-get install libvulkan-dev:i386 (Sorry output -> French. I translated that ;) ): 

The following packages contain unmet dependencies:
 libvulkan-dev: i386: Depends: vulkan-headers: i386 (= 1.1.121.0 ~ rc2-1lunarg18.04.1.1) but it is not installable

And sudo apt-get install vulkan-headers:i386:

No version of the package vulkan-headers: i386 is available, but it exists in the database
of data. This usually means that the package is missing, has become obsolete
or that it is only available from another source
However, the following packages replace it:
  libvulkan-dev libvulkan-dev: i386

E: The "vulkan-headers: i386" package does not have a version that can be installed

It's the issue I think ^^'

**Comment by Tk-Glitch** [comment]
Oh yes, looks like it.
I find that one very confusing considering `libvulkan-dev: i386: Depends: vulkan-headers: i386` :
```
However, the following packages replace it:
libvulkan-dev libvulkan-dev: i386
```
Ubuntu being Ubuntu again :/

**Comment by Tk-Glitch** [comment]
I would assume libvulkan-dev is installed already?

**Comment by jona-1993** [comment]
I fixed that with aptitude command. (Downgrade)

now, when I launch the script:

Hunk #1 succeeded at 2482 (offset -95 lines).
 -> Applying usvfs.patch
patching file dlls/kernel32/file.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file dlls/kernel32/file.c.rej
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

**Comment by Tk-Glitch** [comment]
Pull the latest changes, that one was fixed in https://github.com/Tk-Glitch/PKGBUILDS/commit/ae532f8fd55a2cc9a731f10cdcfd6be7453d5165

**Comment by jona-1993** [comment]
It's OK. It compile. I will make some coffe now ;)

**Comment by jona-1993** [comment]
I have my wine build. But the game shop still doesn't work..

**Comment by Tk-Glitch** [comment]
log?

**Comment by jona-1993** [comment]
https://pastebin.com/mqyc910e

**Comment by Tk-Glitch** [comment]
Except for the locale issues already mentioned by fluffykittyrevenge, there's nothing obvious jumping at me. Does it still work without D9VK? If it does everything points at a D9VK issue.

**Comment by jona-1993** [comment]
Yes, without D9VK, it works. It's a D9VK issue, so?

**Comment by Tk-Glitch** [comment]
Maybe I'd try a rebuild of wine with `_childwindow_fix="true"` in your cfg first.

**Comment by jona-1993** [comment]
Josh say: it's not possible for a D9VK issue ;)

I will test that.
